spring:
  application:
    name: wx-taro-shop-admin-0326
  datasource:
    url: jdbc:postgresql://localhost:5432/wx_taro_shop?currentSchema=public
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


wechat:
  miniapp:
    appid: wxa0000000000000000
    secret: <KEY>
token:
  exp-second: 30
web:
  interceptor:
    public-urls:
      - /wxLogin/code2Session
logging:
  level:
    root: debug
    sql: debug

