spring:
  application:
    name: wx-taro-shop-admin-0326
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

wechat:
  miniapp:
    appid: wxa0000000000000000
    secret: <KEY>
token:
  exp-second: 30
web:
  interceptor:
    public-urls:
      - /wxLogin/code2Session
